[2025-05-07 17:44:38,986: INFO: main: >>>>>>> stage: Data Ingestion Stage started <<<<<<<<]
[2025-05-07 17:44:38,989: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:44:38,990: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:44:38,992: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:44:38,994: INFO: common: artifacts directory created]
[2025-05-07 17:44:38,994: INFO: common: artifacts/data_ingestion directory created]
[2025-05-07 17:44:39,926: INFO: data_ingestion: artifacts/data_ingestion/data.zip downloaded with the following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1DC6:10E4DD:4AD6E2:56744D:681BC3C1
Accept-Ranges: bytes
Date: Wed, 07 May 2025 21:44:39 GMT
Via: 1.1 varnish
X-Served-By: cache-yyz4568-YYZ
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1746654280.749915,VS0,VE0
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 147dfb41aa2e52a0e481019e49bc1c4a45ff1f19
Expires: Wed, 07 May 2025 21:49:39 GMT
Source-Age: 288

]
[2025-05-07 17:44:39,927: INFO: data_ingestion: Dataset is unzipped!]
[2025-05-07 17:44:39,927: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<< 

x========x]
[2025-05-07 17:44:39,927: INFO: main: >>>>>>> stage: Data Validation Stage started <<<<<<<<]
[2025-05-07 17:44:39,929: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:44:39,930: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:44:39,932: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:44:39,932: INFO: common: artifacts directory created]
[2025-05-07 17:44:39,933: INFO: common: artifacts/data_validation directory created]
[2025-05-07 17:44:39,938: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<< 

x========x]
[2025-05-07 17:44:39,938: INFO: main: >>>>>>> stage: Data Transformation Stage started <<<<<<<<]
[2025-05-07 17:44:39,941: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:44:39,942: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:44:39,944: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:44:39,944: INFO: common: artifacts directory created]
[2025-05-07 17:44:39,945: INFO: common: artifacts/data_transformation directory created]
[2025-05-07 17:44:39,962: INFO: data_transformation: Splitted data into train and test sets]
[2025-05-07 17:44:39,962: INFO: data_transformation: Training data shape: (1199, 12)]
[2025-05-07 17:44:39,962: INFO: data_transformation: Test data shape: (400, 12)]
[2025-05-07 17:44:39,962: INFO: main: >>>>>> stage Data Transformation Stage completed <<<<<< 

x========x]
[2025-05-07 17:44:39,962: INFO: main: >>>>>>> stage: Model Training Stage started <<<<<<<<]
[2025-05-07 17:44:39,965: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:44:39,966: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:44:39,967: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:44:39,967: INFO: common: artifacts directory created]
[2025-05-07 17:44:39,968: INFO: common: artifacts/model_trainer directory created]
[2025-05-07 17:44:39,979: INFO: main: >>>>>> stage Model Training Stage completed <<<<<< 

x========x]
[2025-05-07 17:44:39,979: INFO: main: >>>>>>> stage: Model Evaluation Stage started <<<<<<<<]
[2025-05-07 17:44:39,982: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:44:39,983: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:44:39,985: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:44:39,985: INFO: common: artifacts directory created]
[2025-05-07 17:44:39,986: INFO: common: artifacts/model_evaluation directory created]
[2025-05-07 17:44:40,812: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "/home/sermengi/test-github-actions/main.py", line 62, in <module>
    obj.initiate_model_evaluation()
  File "/home/sermengi/test-github-actions/src/datascience/pipeline/model_evaluation_pipeline.py", line 16, in initiate_model_evaluation
    model_evaluation.log_metrics_to_mlflow()
  File "/home/sermengi/test-github-actions/src/datascience/components/model_evaluation.py", line 39, in log_metrics_to_mlflow
    with mlflow.start_run():
  File "/home/sermengi/test-github-actions/venv/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 446, in start_run
    active_run_obj = client.create_run(
  File "/home/sermengi/test-github-actions/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 418, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "/home/sermengi/test-github-actions/venv/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 170, in create_run
    return self.store.create_run(
  File "/home/sermengi/test-github-actions/venv/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 220, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/home/sermengi/test-github-actions/venv/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/sermengi/test-github-actions/venv/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 402, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/sermengi/test-github-actions/venv/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 265, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-05-07 17:45:36,979: INFO: main: >>>>>>> stage: Data Ingestion Stage started <<<<<<<<]
[2025-05-07 17:45:36,982: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:45:36,983: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:45:36,985: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:45:36,986: INFO: common: artifacts directory created]
[2025-05-07 17:45:36,986: INFO: common: artifacts/data_ingestion directory created]
[2025-05-07 17:45:36,986: INFO: data_ingestion: File already exists]
[2025-05-07 17:45:36,986: INFO: data_ingestion: Dataset is already unzipped!]
[2025-05-07 17:45:36,986: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<< 

x========x]
[2025-05-07 17:45:36,986: INFO: main: >>>>>>> stage: Data Validation Stage started <<<<<<<<]
[2025-05-07 17:45:36,989: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:45:36,990: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:45:36,991: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:45:36,992: INFO: common: artifacts directory created]
[2025-05-07 17:45:36,992: INFO: common: artifacts/data_validation directory created]
[2025-05-07 17:45:36,996: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<< 

x========x]
[2025-05-07 17:45:36,997: INFO: main: >>>>>>> stage: Data Transformation Stage started <<<<<<<<]
[2025-05-07 17:45:36,999: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:45:36,999: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:45:37,001: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:45:37,001: INFO: common: artifacts directory created]
[2025-05-07 17:45:37,001: INFO: common: artifacts/data_transformation directory created]
[2025-05-07 17:45:37,019: INFO: data_transformation: Splitted data into train and test sets]
[2025-05-07 17:45:37,019: INFO: data_transformation: Training data shape: (1199, 12)]
[2025-05-07 17:45:37,019: INFO: data_transformation: Test data shape: (400, 12)]
[2025-05-07 17:45:37,019: INFO: main: >>>>>> stage Data Transformation Stage completed <<<<<< 

x========x]
[2025-05-07 17:45:37,019: INFO: main: >>>>>>> stage: Model Training Stage started <<<<<<<<]
[2025-05-07 17:45:37,023: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:45:37,024: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:45:37,025: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:45:37,026: INFO: common: artifacts directory created]
[2025-05-07 17:45:37,027: INFO: common: artifacts/model_trainer directory created]
[2025-05-07 17:45:37,037: INFO: main: >>>>>> stage Model Training Stage completed <<<<<< 

x========x]
[2025-05-07 17:45:37,037: INFO: main: >>>>>>> stage: Model Evaluation Stage started <<<<<<<<]
[2025-05-07 17:45:37,039: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-07 17:45:37,040: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:45:37,042: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-07 17:45:37,042: INFO: common: artifacts directory created]
[2025-05-07 17:45:37,042: INFO: common: artifacts/model_evaluation directory created]
[2025-05-07 17:45:37,849: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-05-07 17:45:45,698: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<< 

x========x]
[2025-05-12 14:17:41,075: INFO: main: >>>>>>> stage: Data Ingestion Stage started <<<<<<<<]
[2025-05-12 14:17:41,078: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-12 14:17:41,079: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 14:17:41,080: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-12 14:17:41,080: INFO: common: artifacts directory created]
[2025-05-12 14:17:41,080: INFO: common: artifacts/data_ingestion directory created]
[2025-05-12 14:17:41,926: INFO: data_ingestion: artifacts/data_ingestion/data.zip downloaded with the following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D03E:70CFC:1767EEB:1C189A0:68223B43
Accept-Ranges: bytes
Date: Mon, 12 May 2025 18:17:41 GMT
Via: 1.1 varnish
X-Served-By: cache-yyz4536-YYZ
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1747073861.067483,VS0,VE320
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: e460314aeac3879875b88b8aeccb21fa31714b95
Expires: Mon, 12 May 2025 18:22:41 GMT
Source-Age: 0

]
[2025-05-12 14:17:41,927: INFO: data_ingestion: Dataset is unzipped!]
[2025-05-12 14:17:41,927: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<< 

x========x]
[2025-05-12 14:17:41,928: INFO: main: >>>>>>> stage: Data Validation Stage started <<<<<<<<]
[2025-05-12 14:17:41,929: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-12 14:17:41,930: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 14:17:41,930: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-12 14:17:41,931: INFO: common: artifacts directory created]
[2025-05-12 14:17:41,931: INFO: common: artifacts/data_validation directory created]
[2025-05-12 14:17:41,938: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<< 

x========x]
[2025-05-12 14:17:41,938: INFO: main: >>>>>>> stage: Data Transformation Stage started <<<<<<<<]
[2025-05-12 14:17:41,939: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-12 14:17:41,940: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 14:17:41,940: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-12 14:17:41,940: INFO: common: artifacts directory created]
[2025-05-12 14:17:41,941: INFO: common: artifacts/data_transformation directory created]
[2025-05-12 14:17:41,956: INFO: data_transformation: Splitted data into train and test sets]
[2025-05-12 14:17:41,956: INFO: data_transformation: Training data shape: (1199, 12)]
[2025-05-12 14:17:41,956: INFO: data_transformation: Test data shape: (400, 12)]
[2025-05-12 14:17:41,956: INFO: main: >>>>>> stage Data Transformation Stage completed <<<<<< 

x========x]
[2025-05-12 14:17:41,956: INFO: main: >>>>>>> stage: Model Training Stage started <<<<<<<<]
[2025-05-12 14:17:41,957: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-12 14:17:41,958: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 14:17:41,959: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-12 14:17:41,959: INFO: common: artifacts directory created]
[2025-05-12 14:17:41,960: INFO: common: artifacts/model_trainer directory created]
[2025-05-12 14:17:41,970: INFO: main: >>>>>> stage Model Training Stage completed <<<<<< 

x========x]
[2025-05-12 14:17:41,971: INFO: main: >>>>>>> stage: Model Evaluation Stage started <<<<<<<<]
[2025-05-12 14:17:41,972: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-05-12 14:17:41,973: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 14:17:41,974: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-05-12 14:17:41,974: INFO: common: artifacts directory created]
[2025-05-12 14:17:41,974: INFO: common: artifacts/model_evaluation directory created]
[2025-05-12 14:17:42,415: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-05-12 14:17:49,057: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<< 

x========x]
[2025-05-12 15:11:58,183: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.21.217.17:8080]
[2025-05-12 15:11:58,184: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-05-12 15:12:02,307: INFO: _internal: 127.0.0.1 - - [12/May/2025 15:12:02] "GET / HTTP/1.1" 200 -]
[2025-05-12 15:12:02,398: INFO: _internal: 127.0.0.1 - - [12/May/2025 15:12:02] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -]
[2025-05-12 15:12:02,554: INFO: _internal: 127.0.0.1 - - [12/May/2025 15:12:02] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-05-12 15:13:49,375: INFO: _internal: 127.0.0.1 - - [12/May/2025 15:13:49] "POST /predict HTTP/1.1" 200 -]
[2025-05-12 15:14:49,667: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.21.217.17:8080]
[2025-05-12 15:14:49,667: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-05-12 15:14:52,066: INFO: _internal: 172.21.208.1 - - [12/May/2025 15:14:52] "GET / HTTP/1.1" 200 -]
[2025-05-12 15:14:52,171: INFO: _internal: 172.21.208.1 - - [12/May/2025 15:14:52] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -]
[2025-05-12 15:14:52,199: INFO: _internal: 172.21.208.1 - - [12/May/2025 15:14:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-05-12 15:15:05,205: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a TypeError.
[2025-05-12 15:15:05,207: INFO: _internal: 172.21.208.1 - - [12/May/2025 15:15:05] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-05-12 15:17:56,495: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a TypeError.
[2025-05-12 15:17:56,496: INFO: _internal: 172.21.208.1 - - [12/May/2025 15:17:56] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-05-12 15:17:58,100: INFO: _internal: 172.21.208.1 - - [12/May/2025 15:17:58] "GET /predict HTTP/1.1" 200 -]
[2025-05-12 15:17:58,119: INFO: _internal: 172.21.208.1 - - [12/May/2025 15:17:58] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -]
[2025-05-12 15:18:12,947: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sermengi/test-github-actions/venv/lib/python3.12/site-packages/flask/app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a TypeError.
[2025-05-12 15:18:12,948: INFO: _internal: 172.21.208.1 - - [12/May/2025 15:18:12] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-05-12 15:18:58,532: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.21.217.17:8080]
[2025-05-12 15:18:58,532: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-05-12 15:19:00,264: INFO: _internal: 127.0.0.1 - - [12/May/2025 15:19:00] "GET / HTTP/1.1" 200 -]
[2025-05-12 15:19:00,358: INFO: _internal: 127.0.0.1 - - [12/May/2025 15:19:00] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -]
[2025-05-12 15:19:00,384: INFO: _internal: 127.0.0.1 - - [12/May/2025 15:19:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-05-12 15:19:15,560: INFO: _internal: 127.0.0.1 - - [12/May/2025 15:19:15] "POST /predict HTTP/1.1" 200 -]
